version: '3.7'

services:
  app:
    image: ${ecr_base_url}/${ecr_image}
    init: true
    restart: always
    env_file: ./.env
    healthcheck:
      test: ["CMD", "./healthcheck.py", "/var/run/gunicorn/gunicorn.sock"]
    volumes:
      - backend-static:/root/src/static
      - gunicorn-socket:/var/run/gunicorn
      - ./media:/root/src/media
    logging: &app_logging
      driver: awslogs
      options:
        awslogs-region: ${region}
        awslogs-group: /aws/ec2/${name}-${env}
        tag: '$${INSTANCE_ID_SUBST}-app'
        awslogs-create-group: "true"

  backups:
    build:
      context: backups/
      dockerfile: Dockerfile
    init: true
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BACKUP_LOCAL_DIR=/var/backups
      - BACKUP_LOCAL_ROTATE_KEEP_LAST=${BACKUP_LOCAL_ROTATE_KEEP_LAST}
      - BACKUP_B2_BUCKET=${BACKUP_B2_BUCKET}
      - BACKUP_B2_KEY_ID=${BACKUP_B2_KEY_ID}
      - BACKUP_B2_KEY_SECRET=${BACKUP_B2_KEY_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_TARGET=${EMAIL_TARGET}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - backups:/var/backups
    logging:
      <<: *app_logging


  nginx:
    image: 'ghcr.io/reef-technologies/nginx-rt:v1.2.2'
    restart: unless-stopped
    healthcheck:
      test: wget -q --spider http://0.0.0.0:8000/admin/login/ || exit 1
    depends_on:
      - app
    command: nginx -g 'daemon off;'
    ports:
      - 8000:8000
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/config_helpers:/etc/nginx/config_helpers
      - backend-static:/srv/static:ro
      - ./media:/srv/media:ro
      - ./nginx/monitoring_certs:/etc/monitoring_certs
      - gunicorn-socket:/var/run/gunicorn:ro
    logging:
      driver: awslogs
      options:
        awslogs-region: ${region}
        awslogs-group: /aws/ec2/${name}-${env}
        tag: '$${INSTANCE_ID_SUBST}-nginx'
        awslogs-create-group: "true"
  vulnrelay:
    image: 'ghcr.io/reef-technologies/vulnrelay:latest'
    container_name: vulnrelay
    restart: unless-stopped
    env_file: ./.vuln.env
    environment:
      - METRICS_DIR=/app/metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nodeexporter_collectors:/app/metrics
    logging:
      driver: awslogs
      options:
        awslogs-region: ${region}
        awslogs-group: /aws/ec2/${name}-${env}
        tag: '$${INSTANCE_ID_SUBST}-vulnrelay'
        awslogs-create-group: "true"
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 7200 vulnrelay
    logging:
      driver: awslogs
      options:
        awslogs-region: ${region}
        awslogs-group: /aws/ec2/${name}-${env}
        tag: '$${INSTANCE_ID_SUBST}-vulnrelay'
        awslogs-create-group: "true"

volumes:
  backend-static:
  backups:
  gunicorn-socket:
  nodeexporter_collectors:
